CREATE TABLE IF NOT EXISTS fruits(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, fruit_name VARCHAR(20));

CREATE TABLE IF NOT EXISTS users(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" VARCHAR(20), fruit_id int NOT NULL);

INSERT INTO fruits(fruit_name) VALUES(?);

SELECT * FROM users INNER JOIN fruits ON fruits.id = users.fruit_id;